{
  "openapi": "3.0.0",
  "info": {
    "title": "Demo Credit",
    "description": "Demo Credit is a mobile lending app with wallet functionality for borrowers to receive loans and make repayments.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://{{base_url}}"
    }
  ],
  "components": {
    "securitySchemes": {
      "noauthAuth": {
        "type": "http",
        "scheme": "noauth"
      },
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/": {
      "get": {
        "tags": ["default"],
        "summary": "Base Endpoint",
        "description": "This is the base endpoint for Demo Credit. It is denoted as the `base_url`",
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Security-Policy": {
                "schema": {
                  "type": "string",
                  "example": "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests"
                }
              },
              "Cross-Origin-Opener-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Cross-Origin-Resource-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Origin-Agent-Cluster": {
                "schema": {
                  "type": "string",
                  "example": "?1"
                }
              },
              "Referrer-Policy": {
                "schema": {
                  "type": "string",
                  "example": "no-referrer"
                }
              },
              "Strict-Transport-Security": {
                "schema": {
                  "type": "string",
                  "example": "max-age=15552000; includeSubDomains"
                }
              },
              "X-Content-Type-Options": {
                "schema": {
                  "type": "string",
                  "example": "nosniff"
                }
              },
              "X-DNS-Prefetch-Control": {
                "schema": {
                  "type": "string",
                  "example": "off"
                }
              },
              "X-Download-Options": {
                "schema": {
                  "type": "string",
                  "example": "noopen"
                }
              },
              "X-Frame-Options": {
                "schema": {
                  "type": "string",
                  "example": "SAMEORIGIN"
                }
              },
              "X-Permitted-Cross-Domain-Policies": {
                "schema": {
                  "type": "string",
                  "example": "none"
                }
              },
              "X-XSS-Protection": {
                "schema": {
                  "type": "integer",
                  "example": "0"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "345"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"159-jGLz7fxa39++cFTGTRaEGdoyyOA\""
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 04 Jul 2024 11:26:01 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "code": 200,
                  "status": "success",
                  "message": "okay",
                  "data": {
                    "name": "demo-credit",
                    "version": "0.0.1",
                    "description": "Demo Credit is a mobile lending app with wallet functionality for borrowers to receive loans and make repayments.",
                    "author": "Olusegun Ekoh (sheygs)",
                    "baseUrl": "https://adjutor.lendsqr.com/v2",
                    "port": "8281",
                    "environment": "development"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/signup": {
      "post": {
        "tags": ["default"],
        "summary": "Sign Up",
        "description": "`{{base_url}}/api/v1/auth/signup`\n\nThis endpoint creates a user entry in the data store.  \nReturns a `status_code` of `201`",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "user_name": "bisiade",
                  "email": "bisi@gmail.com",
                  "password": "BisiA135",
                  "phone_number": "+2348056789312"
                }
              }
            }
          }
        },
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Security-Policy": {
                "schema": {
                  "type": "string",
                  "example": "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests"
                }
              },
              "Cross-Origin-Opener-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Cross-Origin-Resource-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Origin-Agent-Cluster": {
                "schema": {
                  "type": "string",
                  "example": "?1"
                }
              },
              "Referrer-Policy": {
                "schema": {
                  "type": "string",
                  "example": "no-referrer"
                }
              },
              "Strict-Transport-Security": {
                "schema": {
                  "type": "string",
                  "example": "max-age=15552000; includeSubDomains"
                }
              },
              "X-Content-Type-Options": {
                "schema": {
                  "type": "string",
                  "example": "nosniff"
                }
              },
              "X-DNS-Prefetch-Control": {
                "schema": {
                  "type": "string",
                  "example": "off"
                }
              },
              "X-Download-Options": {
                "schema": {
                  "type": "string",
                  "example": "noopen"
                }
              },
              "X-Frame-Options": {
                "schema": {
                  "type": "string",
                  "example": "SAMEORIGIN"
                }
              },
              "X-Permitted-Cross-Domain-Policies": {
                "schema": {
                  "type": "string",
                  "example": "none"
                }
              },
              "X-XSS-Protection": {
                "schema": {
                  "type": "integer",
                  "example": "0"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "456"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"1c8-MTvoQHoNUf9uKY0iHMo1qIiLkvs\""
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 04 Jul 2024 11:29:19 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "code": 201,
                  "status": "success",
                  "message": "account created",
                  "data": {
                    "user": {
                      "id": 1,
                      "user_name": "john",
                      "email": "john.doe@gmail.com",
                      "phone_number": "+2348056789312",
                      "created_at": "2024-07-04T10:29:19.000Z",
                      "updated_at": "2024-07-04T10:29:19.000Z"
                    },
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9uYW1lIjoiam9obiIsImVtYWlsIjoiam9obi5kb2VAZ21haWwuY29tIiwiaWF0IjoxNzIwMDkyNTU5LCJleHAiOjE3MjAxNzg5NTl9.KdkPWArfqOUUo634xUHqzclzAEDkaEIOFT1XzKGDNFw"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/wallets/{wallet_id}/deposit": {
      "post": {
        "tags": ["default"],
        "summary": "Fund Account",
        "description": "Endpoint: `{{base_url}}/api/v1/wallets/:wallet_id/deposit`  \nThis endpoint funds a wallet account.\n\nIt takes the `wallet_id` to be funded and the `amount`\n\nReturns a `200` `OK` response",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "amount": "1500"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "wallet_id",
            "in": "path",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "example": "1"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Security-Policy": {
                "schema": {
                  "type": "string",
                  "example": "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests"
                }
              },
              "Cross-Origin-Opener-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Cross-Origin-Resource-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Origin-Agent-Cluster": {
                "schema": {
                  "type": "string",
                  "example": "?1"
                }
              },
              "Referrer-Policy": {
                "schema": {
                  "type": "string",
                  "example": "no-referrer"
                }
              },
              "Strict-Transport-Security": {
                "schema": {
                  "type": "string",
                  "example": "max-age=15552000; includeSubDomains"
                }
              },
              "X-Content-Type-Options": {
                "schema": {
                  "type": "string",
                  "example": "nosniff"
                }
              },
              "X-DNS-Prefetch-Control": {
                "schema": {
                  "type": "string",
                  "example": "off"
                }
              },
              "X-Download-Options": {
                "schema": {
                  "type": "string",
                  "example": "noopen"
                }
              },
              "X-Frame-Options": {
                "schema": {
                  "type": "string",
                  "example": "SAMEORIGIN"
                }
              },
              "X-Permitted-Cross-Domain-Policies": {
                "schema": {
                  "type": "string",
                  "example": "none"
                }
              },
              "X-XSS-Protection": {
                "schema": {
                  "type": "integer",
                  "example": "0"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "202"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"ca-WXpDlpgRu0WHd3W/kNMn1sK2C+M\""
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 04 Jul 2024 11:31:12 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "code": 200,
                  "status": "success",
                  "message": "wallet funded",
                  "data": {
                    "id": 1,
                    "user_id": 1,
                    "currency": "NGN",
                    "balance": "1500.00",
                    "created_at": "2024-07-04T10:30:16.000Z",
                    "updated_at": "2024-07-04T10:31:12.000Z"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/wallets": {
      "post": {
        "tags": ["default"],
        "summary": "Create Wallet",
        "description": "`Endpoint: {{base_url}}/api/v1/wallets`\n\nThis endpoint takes a user account ID `user_id` in `req.body`to create a wallet entry.  \nIt returns a `201` `CREATED` response.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "user_id": "1"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Security-Policy": {
                "schema": {
                  "type": "string",
                  "example": "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests"
                }
              },
              "Cross-Origin-Opener-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Cross-Origin-Resource-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Origin-Agent-Cluster": {
                "schema": {
                  "type": "string",
                  "example": "?1"
                }
              },
              "Referrer-Policy": {
                "schema": {
                  "type": "string",
                  "example": "no-referrer"
                }
              },
              "Strict-Transport-Security": {
                "schema": {
                  "type": "string",
                  "example": "max-age=15552000; includeSubDomains"
                }
              },
              "X-Content-Type-Options": {
                "schema": {
                  "type": "string",
                  "example": "nosniff"
                }
              },
              "X-DNS-Prefetch-Control": {
                "schema": {
                  "type": "string",
                  "example": "off"
                }
              },
              "X-Download-Options": {
                "schema": {
                  "type": "string",
                  "example": "noopen"
                }
              },
              "X-Frame-Options": {
                "schema": {
                  "type": "string",
                  "example": "SAMEORIGIN"
                }
              },
              "X-Permitted-Cross-Domain-Policies": {
                "schema": {
                  "type": "string",
                  "example": "none"
                }
              },
              "X-XSS-Protection": {
                "schema": {
                  "type": "integer",
                  "example": "0"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "200"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"c8-JJPUWIqzRv9PxYbAAzRUn1jKWo4\""
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 04 Jul 2024 11:30:16 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "code": 201,
                  "status": "success",
                  "message": "wallet created",
                  "data": {
                    "id": 1,
                    "user_id": 1,
                    "currency": "NGN",
                    "balance": "0.00",
                    "created_at": "2024-07-04T10:30:16.000Z",
                    "updated_at": "2024-07-04T10:30:16.000Z"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/wallets/initialize-payment": {
      "post": {
        "tags": ["default"],
        "summary": "Initialize Payment",
        "description": "Endpoint: `{{base_url}}/api/v1/wallets/initialize-payment`\n\nThis endpoint is used to fund a wallet through a Paystack payment gateway.  \nIt takes a `wallet_id` and `amount` in the body of the request to return an `authorization_url`\n\nIt returns a `200` `OK` response",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "wallet_id": "1",
                  "amount": 1000
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Security-Policy": {
                "schema": {
                  "type": "string",
                  "example": "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests"
                }
              },
              "Cross-Origin-Opener-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Cross-Origin-Resource-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Origin-Agent-Cluster": {
                "schema": {
                  "type": "string",
                  "example": "?1"
                }
              },
              "Referrer-Policy": {
                "schema": {
                  "type": "string",
                  "example": "no-referrer"
                }
              },
              "Strict-Transport-Security": {
                "schema": {
                  "type": "string",
                  "example": "max-age=15552000; includeSubDomains"
                }
              },
              "X-Content-Type-Options": {
                "schema": {
                  "type": "string",
                  "example": "nosniff"
                }
              },
              "X-DNS-Prefetch-Control": {
                "schema": {
                  "type": "string",
                  "example": "off"
                }
              },
              "X-Download-Options": {
                "schema": {
                  "type": "string",
                  "example": "noopen"
                }
              },
              "X-Frame-Options": {
                "schema": {
                  "type": "string",
                  "example": "SAMEORIGIN"
                }
              },
              "X-Permitted-Cross-Domain-Policies": {
                "schema": {
                  "type": "string",
                  "example": "none"
                }
              },
              "X-XSS-Protection": {
                "schema": {
                  "type": "integer",
                  "example": "0"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "140"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"8c-kXc0X7PYZhzRAxsJl2hB/nLH2xE\""
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 04 Jul 2024 11:32:03 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "code": 200,
                  "status": "success",
                  "message": "payment initialized",
                  "data": {
                    "authorization_url": "https://checkout.paystack.com/3lq2muovwihj371"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/wallets/deposit": {
      "post": {
        "tags": ["default"],
        "summary": "Credit Wallet [With Payment Gateway]",
        "description": "Endpoint: `{{base_url}}/api/v1/wallets/deposit`\n\nThis endpoint takes in `reference` in the request body to fund the wallet account\n\nIt returns a `200` `OK` response",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "reference": "o3xq5mq9kj"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Security-Policy": {
                "schema": {
                  "type": "string",
                  "example": "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests"
                }
              },
              "Cross-Origin-Opener-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Cross-Origin-Resource-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Origin-Agent-Cluster": {
                "schema": {
                  "type": "string",
                  "example": "?1"
                }
              },
              "Referrer-Policy": {
                "schema": {
                  "type": "string",
                  "example": "no-referrer"
                }
              },
              "Strict-Transport-Security": {
                "schema": {
                  "type": "string",
                  "example": "max-age=15552000; includeSubDomains"
                }
              },
              "X-Content-Type-Options": {
                "schema": {
                  "type": "string",
                  "example": "nosniff"
                }
              },
              "X-DNS-Prefetch-Control": {
                "schema": {
                  "type": "string",
                  "example": "off"
                }
              },
              "X-Download-Options": {
                "schema": {
                  "type": "string",
                  "example": "noopen"
                }
              },
              "X-Frame-Options": {
                "schema": {
                  "type": "string",
                  "example": "SAMEORIGIN"
                }
              },
              "X-Permitted-Cross-Domain-Policies": {
                "schema": {
                  "type": "string",
                  "example": "none"
                }
              },
              "X-XSS-Protection": {
                "schema": {
                  "type": "integer",
                  "example": "0"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"671-Uoc7+T9mJKcIGkRibVS/9R5dkBw\""
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 04 Jul 2024 11:47:00 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              },
              "Transfer-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "chunked"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "code": 200,
                  "status": "success",
                  "message": "wallet funded",
                  "data": {
                    "status": true,
                    "message": "Verification successful",
                    "data": {
                      "id": 3946879891,
                      "domain": "test",
                      "status": "success",
                      "reference": "1itqz14fxa",
                      "receipt_number": null,
                      "amount": 1000,
                      "message": null,
                      "gateway_response": "Successful",
                      "paid_at": "2024-07-04T11:32:45.000Z",
                      "created_at": "2024-07-04T11:32:03.000Z",
                      "channel": "card",
                      "currency": "NGN",
                      "ip_address": "102.219.153.212",
                      "metadata": {
                        "amount": "1000",
                        "wallet_id": "1",
                        "user_id": "1",
                        "currency": "NGN"
                      },
                      "log": {
                        "start_time": 1720092744,
                        "time_spent": 23,
                        "attempts": 1,
                        "errors": 0,
                        "success": true,
                        "mobile": false,
                        "input": [],
                        "history": [
                          {
                            "type": "action",
                            "message": "Attempted to pay with card",
                            "time": 21
                          },
                          {
                            "type": "success",
                            "message": "Successfully paid with card",
                            "time": 23
                          }
                        ]
                      },
                      "fees": 15,
                      "fees_split": null,
                      "authorization": {
                        "authorization_code": "AUTH_776l0v47rx",
                        "bin": "408408",
                        "last4": "4081",
                        "exp_month": "12",
                        "exp_year": "2030",
                        "channel": "card",
                        "card_type": "visa ",
                        "bank": "TEST BANK",
                        "country_code": "NG",
                        "brand": "visa",
                        "reusable": true,
                        "signature": "SIG_yypN86wTD58Y0eNNc17N",
                        "account_name": null,
                        "receiver_bank_account_number": null,
                        "receiver_bank": null
                      },
                      "customer": {
                        "id": 173576349,
                        "first_name": null,
                        "last_name": null,
                        "email": "john.doe@gmail.com",
                        "customer_code": "CUS_n1vf1e83yvpfc55",
                        "phone": null,
                        "metadata": null,
                        "risk_action": "default",
                        "international_format_phone": null
                      },
                      "plan": null,
                      "split": {},
                      "order_id": null,
                      "paidAt": "2024-07-04T11:32:45.000Z",
                      "createdAt": "2024-07-04T11:32:03.000Z",
                      "requested_amount": 1000,
                      "pos_transaction_data": null,
                      "source": null,
                      "fees_breakdown": null,
                      "connect": null,
                      "transaction_date": "2024-07-04T11:32:03.000Z",
                      "plan_object": {},
                      "subaccount": {}
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/transfers": {
      "post": {
        "tags": ["default"],
        "summary": "Transfer to Wallet",
        "description": "Endpoint: `http://localhost:8281/api/v1/transfers`\n\nThis endpoint transfers funds from a source wallet to a destination wallet\n\nIt accepts `source_wallet_id`, `destination_wallet_id` and `amount` as request bodies.\n\nIt returns a `200` `OK` response.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "source_wallet_id": "4",
                  "destination_wallet_id": "5",
                  "amount": "1000"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Security-Policy": {
                "schema": {
                  "type": "string",
                  "example": "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests"
                }
              },
              "Cross-Origin-Opener-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Cross-Origin-Resource-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Origin-Agent-Cluster": {
                "schema": {
                  "type": "string",
                  "example": "?1"
                }
              },
              "Referrer-Policy": {
                "schema": {
                  "type": "string",
                  "example": "no-referrer"
                }
              },
              "Strict-Transport-Security": {
                "schema": {
                  "type": "string",
                  "example": "max-age=15552000; includeSubDomains"
                }
              },
              "X-Content-Type-Options": {
                "schema": {
                  "type": "string",
                  "example": "nosniff"
                }
              },
              "X-DNS-Prefetch-Control": {
                "schema": {
                  "type": "string",
                  "example": "off"
                }
              },
              "X-Download-Options": {
                "schema": {
                  "type": "string",
                  "example": "noopen"
                }
              },
              "X-Frame-Options": {
                "schema": {
                  "type": "string",
                  "example": "SAMEORIGIN"
                }
              },
              "X-Permitted-Cross-Domain-Policies": {
                "schema": {
                  "type": "string",
                  "example": "none"
                }
              },
              "X-XSS-Protection": {
                "schema": {
                  "type": "integer",
                  "example": "0"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "274"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"112-GGbIcGTp5fXRDVo4bqzd5WPIi34\""
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 04 Jul 2024 11:49:00 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "code": 200,
                  "status": "success",
                  "message": "transfer successful",
                  "data": {
                    "id": 9,
                    "source_wallet_id": 1,
                    "destination_wallet_id": 2,
                    "amount": "1000.00",
                    "transaction_type": "transfer",
                    "status": "success",
                    "created_at": "2024-07-04T10:49:00.000Z",
                    "updated_at": "2024-07-04T10:49:00.000Z"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/withdrawals": {
      "post": {
        "tags": ["default"],
        "summary": "Disbursement to External Account",
        "description": "Endpoint: `http://localhost:8281/api/v1/withdrawals`\n\nThis endpoint transfers funds from a source wallet to a destination wallet\n\nIt accepts `wallet_id` and `amount` as request bodies.\n\nIt returns a `200` `OK` response.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "wallet_id": "1",
                  "amount": "1000"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Security-Policy": {
                "schema": {
                  "type": "string",
                  "example": "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests"
                }
              },
              "Cross-Origin-Opener-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Cross-Origin-Resource-Policy": {
                "schema": {
                  "type": "string",
                  "example": "same-origin"
                }
              },
              "Origin-Agent-Cluster": {
                "schema": {
                  "type": "string",
                  "example": "?1"
                }
              },
              "Referrer-Policy": {
                "schema": {
                  "type": "string",
                  "example": "no-referrer"
                }
              },
              "Strict-Transport-Security": {
                "schema": {
                  "type": "string",
                  "example": "max-age=15552000; includeSubDomains"
                }
              },
              "X-Content-Type-Options": {
                "schema": {
                  "type": "string",
                  "example": "nosniff"
                }
              },
              "X-DNS-Prefetch-Control": {
                "schema": {
                  "type": "string",
                  "example": "off"
                }
              },
              "X-Download-Options": {
                "schema": {
                  "type": "string",
                  "example": "noopen"
                }
              },
              "X-Frame-Options": {
                "schema": {
                  "type": "string",
                  "example": "SAMEORIGIN"
                }
              },
              "X-Permitted-Cross-Domain-Policies": {
                "schema": {
                  "type": "string",
                  "example": "none"
                }
              },
              "X-XSS-Protection": {
                "schema": {
                  "type": "integer",
                  "example": "0"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "282"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"11a-G626y6/JjYIeqhj9JMOWNQ4UfN4\""
                }
              },
              "Vary": {
                "schema": {
                  "type": "string",
                  "example": "Accept-Encoding"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 04 Jul 2024 11:49:33 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "code": 200,
                  "status": "success",
                  "message": "withdrawal successful",
                  "data": {
                    "id": 10,
                    "source_wallet_id": 1,
                    "destination_wallet_id": null,
                    "amount": "1000.00",
                    "transaction_type": "withdrawal",
                    "status": "success",
                    "created_at": "2024-07-04T10:49:33.000Z",
                    "updated_at": "2024-07-04T10:49:33.000Z"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
